# version: 2.1
# orbs:
#   python: circleci/python@1.5.0

# jobs:
#   build-and-test: # This is the name of the job, feel free to change it to better match what you're trying to do!
#     docker:
#       - image: cimg/python:3.10.2

#     steps:
#       - checkout
#       - python/install-packages:
#           pkg-manager: pip
#       - run:
#           name: test
#           command: PYTHONPATH=. py.test
# workflows:
#   sample: # This is the name of the workflow, feel free to change it to better match your workflow.
#     jobs:
#       - build-and-test
version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'